### ISSUE TITLE
create branch 4 off of branch 3

### ISSUE THREAD

**Issue by radam13** [helmar-brewing/HB#106]
Steve, can you please create branch 4 (new branch) based on branch 3?  i can then add requests via that. thanks!

initial things i want to do:
- on stripe change paper/digital to new pricing
- convert paper to paper/digital
- leave digital only alone
- on webpage - show TWO options - paper/digital , free - i can edit text
- on webpage - update styling for 2 columns

**Comment by iamstev** [comment]
I've created a new branch called "subscription update". I've also created a new milestone called "Subscription Update". That was can assign related tasks to.  I have also switch the test server to deploy the subscription update branch instead of the version-3 branch.
