### ISSUE TITLE
Set Due Date

### ISSUE THREAD

**Issue by iamstev** [helmar-brewing/HB#107]
Decide on an estimated launch date, and set the milestone due date for Subscription Update. We can change it later if needed, but we should have some idea of the timeline.

**Comment by radam13** [comment]
Steve, I hope it's not too soon, but I'd like due date as June 1 (tomorrow) as far as going into effect. the first renewals are not out until June 16.

I think first step is we can just update the webpage to show only the digital/paper and remove the other 2 options. also, we'll need to update the Stripe digital/paper to $39.99

next step to happen would be converting people to digital/paper who are paper now.

i will work on a communication very very soon. if you're busy today, i can take a look at switching the step 1 tonight (no problem for me)
