### ISSUE TITLE
Auction Times

### ISSUE THREAD

**Issue by iamstev** [helmar-brewing/HB#21]
When are auctions usually posted?

It looks like last weeks auctions were post Wednesday evening, so they are showing up as current auctions on the site this morning.

Perhaps we should use the auction end time, instead of auction start time for determining the auctions to list on the front page. With the eBay API Can we just select all actions that end later than right now?

**Comment by radam13** [comment]
Steve, i can take a look tonight ... but didn't this code work before? i think you need to look back in time. i had it minus 1 week and that seemed to work on his server when auctions were updating. auctions start/end tuesday evenings. if you look back more than 1 week (and 2 minutes) you'll see completed auctions. also, if you look forward, i *think* it pulls in auctions he has pre-loaded that are about to start next week (he loads them early with a start time in the future). you could look back 2 weeks, but you'll need to filter out XX auctions (80-120) and THEN start displaying 8 at a time.  so what do you think changed or is not working?

**Comment by iamstev** [comment]
The code is working exactly as you intended. I think the problem is that some auctions for last week were started Wednesday morning, so they were still showing up this morning (they are no longer showing up).

**Comment by radam13** [comment]
He sets his auctions for a 7 day period, so i think the code is good. He may start an auction outside of his process (he automates it to start every 2 minutes starting around 9/10pm), but it's very rare. he may also have an auction that is not 7 days. i think the code breaks if it's not a 7 day auction :) but again, extremely rare

**Comment by iamstev** [comment]
okay. working as intended.
