### ISSUE TITLE
issue with user not logged in

### ISSUE THREAD

**Issue by radam13** [helmar-brewing/HB#28]
very wierd issue. i was signed in as testuser1. charles was on phone also signed in. i'm at my test page http://helmarbrewing.com/test/user_checklist.php  ...  i scroll down to bottom of page and the page just refreshes with error "Sorry, you do not have a paid membership! Please checkout our paid subscriptions so you can view your personal Helmar card art checklist!" . this is the only error with this text in that file. but i didn't click anything ( i dont think i did), it just seemed to update on its own!! also, i had charles sign in via accounts (remember, all our log in / log off links are hidden on the production version). his first error was what i got, you need active. then he refreshed and got an error about connecting to stripe. third refresh and he was fine.  but my issue was definitely wierd

**Comment by iamstev** [comment]
I upgraded the stripe library, and plan on making another change to the way we check for subscription, hopefully we won't see more issues.  Leaving open for now.

**Comment by iamstev** [comment]
I am pretty sure this is worked out with the updates.
