### ISSUE TITLE
eBay field for registration

### ISSUE THREAD

**Issue by radam13** [helmar-brewing/HB#29]
Steve, can you add text field to the account process? we would like to capture their ebay ID. if they don't have one, they can leave blank. or, it not too much work, have a check box if they have an ID then an input box shows. that might reduce the "i don't have an ebay id" instead of just keeping it blank. in the user table i added "ebayID" as varchar(40). thanks!

**Comment by iamstev** [comment]
possible language: "link my eBay account"

**Comment by radam13** [comment]
for now, i don't think i want to have that text. i would ike to capture it. see, i could write a script that will pull in data based on user (i would have to play around with things on my end too), but my concern would be that they could enter anyone's screen name. unless we can use some ebay API to check a match (have them login to ebay). ideally that all works and we have a button and it will run. also, i could do a cron job in the future that will update future. see, we would like to capture so we can automatically update their personal card list. for now though, it's informational.

**Comment by iamstev** [comment]
we are now capturing eBay usernames on registration, still need to add a way for users to change their username on the account page.

**Comment by iamstev** [comment]
This is done.
