### ISSUE TITLE
Updating subscription text and popups

### ISSUE THREAD

**Issue by radam13** [helmar-brewing/HB#44]
i wrote this in a word doc, but can only attach pics...
When signing up for a paid plan
Would like an extra “OK, are you sure” type box. How about:
“You are signup up for SUBSCRIPTION_PLAN. You will pay for the full year subscription that will renew on DATE. When you downgrade your subscription your plan will change on your next renewal date. When you upgrade your subscription your current subscription will end and your new subscription will begin immediately. Click proceed to continue with your purchase”
That might be a little wordy…..

If you’re getting a free plan as just email (do they need to click on it or do they have it with registration?). if there was a popup box, maybe we say “Thank you for your free subscription. If you enjoy our website, please consider our subscription plans!” … I didn’t check, once they register, is the free version automatically checked on their account page? If so, maybe we don’t worry about that text

Downgrading Subscription
CURRENT POPUP TEXT:
Subscription Status
You have reduced your subscription to Paper Magazine.
You can continue to enjoy your current benefits until 06-04-2016.
Your credit card was not charged.
Your subscription will renew on 06/04/2016.

NEW POPUP TEXT:
Pre-status change:
You are changing your subscription. You will continue to have your current benefits until  DATE.  Your new  subscription benefits will be available on your renewal date of DATE.  Your credit card will not be charged at this time.
Confirm, Cancel

Subscription Status
You have changed your subscription to Paper Magazine. You will receive these benefits on your next renewal date of  06/04/2016. Your credit card will not be charged at this time.
You can continue to enjoy your current benefits (CURRENT SUBSCRIPTION)  until 06/04/2016
 (do we add 2 buttons : “I agree” or “Cancel  Changes” ? )

Text in box at bottom of account page:

CURRENT TEXT BOX:
You are currently subscribed to Digital + Paper Magazine
You have elected to change your subscription to Paper Magazine.
Enjoy your current benefits until Jun 4 2016.
Next Payment: $29.95 on Jun 4 2016.

NEW TEXT BOX:
You are currently subscribed to Digital + Paper Magazine until Jun 4, 2016
You have elected to change your subscription to Paper Magazine effective Jun 4, 2016
Next Payment: $29.95 on Jun 4 2016.

Note: will this text change on june 4 / 5 2016 once the change have gone into effect?

UPGRADING SERVICE
CURRENT POPUP TEXT:
Subscription Status
Thank you for upgrading to Digital + Paper Magazine
Your credit card was charged $5.00
Your subscription will renew on 06/09/2016.

NEW POPUP TEXT: (I don’t think we need to change much)
Pre-status change:
You are upgrading your subscription. New benefits will be available immediately. Your credit card will be charged $$$$ upon acceptance.
Confirm, Cancel
Subscription Status
Thank you for upgrading to Digital + Paper Magazine. Your benefits will be in effect immediately.
Your credit card was charged $5.00
Your subscription will renew on 06/09/2016.

the textbox text seems fine

**Comment by iamstev** [comment]
> …I didn’t check, once they register, is the free version automatically checked on their account page?

A free account is just someone who has registered but not chosen anything else. The box is automatically checked.

**Comment by iamstev** [comment]
@radam13 

> will this text change on june 4 / 5 2016 once the change have gone into effect?

yes.
