### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by iamstev** [helmar-brewing/HB#6]
Add twitter link to footer.

**Comment by radam13** [comment]
https://twitter.com/helmarblog/

Steve, i might suggest that charles looks for a different twitter handle that matches more of his brand and less of his blog.

**Comment by radam13** [comment]
would like to close this to keep clean. should i suggest to charles that we remove twitter? he won't be using it often i think (too much to keep up on). or, do we leave the twitter account active in case someone on twitter stumbles on it?

**Comment by iamstev** [comment]
I'd just leave the account active. Make sure there is a link to the website in the profile. That way he has his name reserved.
