### ISSUE TITLE
Account page not showing date

### ISSUE THREAD

**Issue by iamstev** [helmar-brewing/HB#87]
The account page is not showing the date for the next magazine.

http://stev.link/image/1w1Y0u2r0T2z

![image 2015-12-01 at 4 13 17 pm](https://cloud.githubusercontent.com/assets/3354780/11514438/8bd81b2e-9846-11e5-84d6-aea0b1d6cd5f.png)

**Comment by iamstev** [comment]
@radam13 you already fixed this right?

**Comment by radam13** [comment]
yes, fixed! will comment and close
