### ISSUE TITLE
Users not able to enter address or credit card when creating a new account

### ISSUE THREAD

**Issue by iamstev** [helmar-brewing/HB#92]
this happens because the address script is requiring level 2 access so it redirects to the account page.

**Comment by iamstev** [comment]
@radam13 I am fixing this today.  This is HIGH PRIORITY.

**Comment by iamstev** [comment]
fixed. not billing.

**Comment by radam13** [comment]
Steve, what would we see different?  Last night Charles gave me a list 
of users to add. I had 3 I added. The process was:

click Register
enter first/last name, username, password, and ebay tag
then I had to log in (really, re-confirm) and go to account page to 
enter address

so, does this remove the re-confirm login? or, do we enter address while 
signing up?


as an FYI, I'm in the office Mon-Wed this week, then off until January. 
I might need help with the email cron job. I haven't looked at it in a 
few days but I'm going to try my plan B.


thanks!
Robert

**Comment by iamstev** [comment]
This bug removes the reconfirm password, and allows the user to add their address and and credit card info on the subscription page without going to the account page.

You only enter the address if you are signing up for a subscription. If you are not signing up for a paying subscription you would have to continue to go to the account page to add the address. Asking for a users address when we don't need it to send them a magazine will put them off.

This bug would NOT have allowed someone to subscribe to a paper magazine and not enter their address. They would not have been allowed to subscribe until they entered their address on the account page. So this was unrelated to users have subscriptions without addresses.
